# Generated by Django 3.0.5 on 2020-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0012_auto_20200527_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='details',
        ),
        migrations.AddField(
            model_name='orders',
            name='details',
            field=models.ManyToManyField(to='dappx.cartItem'),
        ),
    ]
