# Generated by Django 3.0.5 on 2020-06-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0016_auto_20200602_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='details',
        ),
        migrations.AddField(
            model_name='orders',
            name='details',
            field=models.ManyToManyField(to='dappx.cartItem'),
        ),
    ]
