# Generated by Django 3.0.5 on 2020-06-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0017_auto_20200602_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='details',
            field=models.ManyToManyField(related_name='details', to='dappx.cartItem'),
        ),
    ]
