# Generated by Django 3.0.5 on 2020-06-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0018_auto_20200602_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='details',
            field=models.ManyToManyField(to='dappx.cartItem'),
        ),
    ]
