# Generated by Django 3.0.5 on 2020-04-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productcategories',
            new_name='categories',
        ),
    ]
