# Generated by Django 3.0.5 on 2020-04-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productcategories',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userType',
            fields=[
                ('typeID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('registrationDate', models.DateField()),
                ('phone', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userType')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('productbrand', models.CharField(max_length=100)),
                ('productprice', models.FloatField()),
                ('Quantity', models.CharField(max_length=100)),
                ('ShortDesc', models.CharField(max_length=100)),
                ('LongDesc', models.CharField(max_length=100)),
                ('stock', models.FloatField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productcategories')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(max_length=100)),
                ('shipName', models.CharField(max_length=100)),
                ('shipAddress', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('shipping', models.FloatField(max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('orderdate', models.DateField()),
                ('shipped', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('DetailID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orders')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
    ]
